package forward

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/zeptop-dev/bosun/internal/runas"

	"github.com/zeptop-dev/bosun/internal/core/subprocess"
	"github.com/zeptop-dev/bosun/pkg/spec"
)

// Realm runs the rules with Backend "realm" through one zhboner/realm
// process (a userspace relay written in Rust, popular with nobrand and
// the IPLC crowd for its throughput). bosun generates realm's TOML with
// every realm-backed rule and restarts the process when that set changes;
// the target probes stay bosun's, like the nft backend.
type Realm struct {
	// Binary resolves the realm executable (installing it on first use).
	Binary func(ctx context.Context) (string, error)
	// Dir holds realm.toml.
	Dir string
	Log *slog.Logger

	proc    *subprocess.Supervisor
	applied string // rendered config currently running ("" = stopped)
}

// realmConfig renders the TOML for the given rules, sorted by tag so the
// text is stable. Each rule becomes one endpoint; "both" turns UDP on
// alongside TCP, "udp" turns TCP off.
func realmConfig(rules []spec.Forward) string {
	sorted := append([]spec.Forward(nil), rules...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Tag < sorted[j].Tag })
	var b strings.Builder
	b.WriteString("# generated by bosun; edits are overwritten\n[log]\nlevel = \"warn\"\n\n[network]\nno_tcp = false\nuse_udp = false\n")
	for _, f := range sorted {
		listen := f.Listen
		if listen == "" {
			listen = "0.0.0.0"
		}
		fmt.Fprintf(&b, "\n[[endpoints]]\n# %s\nlisten = %q\nremote = %q\n", f.Tag, net.JoinHostPort(listen, strconv.Itoa(f.Port)), f.Target)
		if len(f.Targets) > 0 {
			// realm balances per connection (no failover; the spec check
			// refuses that combination) with weights for remote first.
			var extra, weights []string
			for i, h := range f.Hops() {
				if i > 0 {
					extra = append(extra, strconv.Quote(h.Target))
				}
				weights = append(weights, strconv.Itoa(h.Weight))
			}
			fmt.Fprintf(&b, "extra_remotes = [%s]\nbalance = \"roundrobin: %s\"\n", strings.Join(extra, ", "), strings.Join(weights, ", "))
		}
		var opts []string
		switch f.Protocol {
		case "udp":
			opts = append(opts, "no_tcp = true", "use_udp = true")
		case "both":
			opts = append(opts, "use_udp = true")
		}
		if f.ProxyProtocol {
			opts = append(opts, "send_proxy = true", "send_proxy_version = 2")
		}
		if len(opts) > 0 {
			b.WriteString("network = { " + strings.Join(opts, ", ") + " }\n")
		}
	}
	return b.String()
}

// apply brings the realm process in line with rules (none = stopped).
func (r *Realm) apply(ctx context.Context, rules []spec.Forward) error {
	if r == nil {
		if len(rules) > 0 {
			return fmt.Errorf("forward: realm backend is not available on this node")
		}
		return nil
	}
	if len(rules) == 0 {
		if r.proc != nil {
			_ = r.proc.Stop(ctx)
			r.proc = nil
		}
		r.applied = ""
		return nil
	}
	cfg := realmConfig(rules)
	if cfg == r.applied && r.proc != nil && r.proc.Running() {
		return nil
	}
	bin, err := r.Binary(ctx)
	if err != nil {
		return fmt.Errorf("forward: realm: %w", err)
	}
	if err := os.MkdirAll(r.Dir, 0o750); err != nil {
		return err
	}
	path := filepath.Join(r.Dir, "realm.toml")
	if err := runas.MkdirRoot(r.Dir); err != nil {
		return err
	}
	if err := runas.WriteFile(path, []byte(cfg), 0o600, true); err != nil {
		return err
	}
	if r.proc != nil {
		_ = r.proc.Stop(ctx)
		r.proc = nil
	}
	log := r.Log
	if log == nil {
		log = slog.Default()
	}
	p := subprocess.New("realm", bin, []string{"-c", path}, r.Dir, log)
	if err := p.Start(ctx); err != nil {
		return fmt.Errorf("forward: realm: %w", err)
	}
	r.proc, r.applied = p, cfg
	return nil
}

// stop ends the process (Manager.Stop).
func (r *Realm) stop(ctx context.Context) {
	if r == nil || r.proc == nil {
		return
	}
	_ = r.proc.Stop(ctx)
	r.proc, r.applied = nil, ""
}

// Running reports whether the realm process is up (doctor).
func (r *Realm) Running() bool { return r != nil && r.proc != nil && r.proc.Running() }
